;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		ergoemacs-undefined
		keyboard-escape-quit
		move-region-up
		my-insert-tab-char
		))

(setq mc/cmds-to-run-once
      '(
		suspend-frame
		))
